name: linux-compile

on:
  workflow_call:
    inputs:
      checkout-repo:
        required: true
        type: string
      checkout-ref:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        os: [linux]
        cpu: [x64, arm64]
        type: [self-contained, no-self-contained]
        include:
           - type: self-contained
             ifSelf: "true"
           - type: no-self-contained
             ifSelf: "false"

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.checkout-repo }}
        ref: ${{ inputs.checkout-ref }}

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-architecture: x64

    - name: Install dependencies
      working-directory: ./src
      run: dotnet restore SyncClipboard.Desktop.Default

    - name: Check code style
      working-directory: ./src
      run: |
        dotnet format SyncClipboard.Desktop --verify-no-changes --no-restore
        dotnet format SyncClipboard.Desktop.Default --verify-no-changes --no-restore

    - name: Check code style info
      working-directory: ./src
      run: |
        dotnet format SyncClipboard.Desktop --verify-no-changes --no-restore --severity info
        dotnet format SyncClipboard.Desktop.Default --verify-no-changes --no-restore --severity info
        exit 0

    # - name
        #  msBuild SyncClipboard.Desktop.Default/SyncClipboard.Desktop.Default.csproj /p:RuntimeIdentifier=osx-arm64 /p:Platform=ARM64 /p:SelfContained=false /p:OutDir=../../osx-arm64-no-self-contained /p:Configuration=Release /t:Publish /v:m  
    - name: Build ${{ matrix.os }}-${{ matrix.cpu }}-${{ matrix.type }} 
      run: |
        msBuild SyncClipboard.Desktop.Default/SyncClipboard.Desktop.Default.csproj /p:RuntimeIdentifier=${{ matrix.os }}-${{ matrix.cpu }} /p:Platform=${{ matrix.cpu }} /p:SelfContained=${{ matrix.ifSelf }} /p:OutDir=../../${{ matrix.os }}-${{ matrix.cpu }}-${{ matrix.type }} /p:Configuration=Release /t:Publish /v:m  
      working-directory: ./src

    - name: Upload ${{ matrix.os }}-${{ matrix.cpu }}-${{ matrix.type }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.cpu }}-${{ matrix.type }}
        path: ${{ matrix.os }}-${{ matrix.cpu }}-${{ matrix.type }}/