name: mac-package

on:
  workflow_call:  
    inputs:
      checkout-repo:
        required: true
        type: string
      checkout-ref:
        required: true
        type: string

jobs:
  package-macos:
    strategy:
      matrix:
        cpu: [x64, arm64]

    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.checkout-repo }}
          ref: ${{ inputs.checkout-ref }}

      - name: Setup software form homebrew
        run: | 
          export HOMEBREW_NO_AUTO_UPDATE=true
          brew install create-dmg tree

      # Install the .NET workload
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x

      - name: Install dotnet workload and dependencies
        working-directory: ./src/SyncClipboard.Desktop.MacOS
        run: |
          dotnet workload install macos
          dotnet workload restore
          dotnet restore

      - name: Check code style
        working-directory: ./src
        run: |
          dotnet format SyncClipboard.Desktop.MacOS --verify-no-changes --no-restore
    
      - name: Check code style info
        working-directory: ./src
        run: |
          dotnet format SyncClipboard.Desktop.MacOS --verify-no-changes --no-restore --severity info
          exit 0
    
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.*

      # - name
          #  dotnet publish SyncClipboard.Desktop.MacOS/SyncClipboard.Desktop.MacOS.csproj -r osx-x64 -c Release
      - name: Build ${{ matrix.cpu }}
        run: |
          dotnet publish SyncClipboard.Desktop.MacOS/SyncClipboard.Desktop.MacOS.csproj -r osx-${{ matrix.cpu }} -c Release
        working-directory: ./src

      - name: Download version
        uses: actions/download-artifact@v4
        with:
          name: version-desktop

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt

      - name: mv app
        run: | 
          mv src/SyncClipboard.Desktop.MacOS/bin/Release/net8.0-macos/osx-${{ matrix.cpu }}/SyncClipboard.Desktop.MacOS.app build/macos/SyncClipboard.app
          chmod +x build/macos/SyncClipboard.app/Contents/MacOS/SyncClipboard.Desktop.MacOS

      - name: Package app
        run: | 
          chmod +x buildAppBundle.sh
          ./buildAppBundle.sh 
        working-directory: ./build/macos

      - name: Package dmg
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 5
          warning_on_retry: false
          retry_on: error
          command: |
            cd ./build/macos
            create-dmg \
            --volicon VolumeIcon.icns \
            --background dmg-background.png \
            --window-size 660 400 \
            --icon-size 120 \
            --icon SyncClipboard.app 165 175 \
            --app-drop-link 495 175 \
            SyncClipboard.dmg SyncClipboard.app

      - name: show folder
        run: |
          ls -l
          tree 
        working-directory: ./build/macos

      - name: Change name
        run: mv SyncClipboard.dmg "SyncClipboard_${{ steps.version.outputs.content }}_macos_${{ matrix.cpu }}.dmg"
        working-directory: ./build/macos

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "SyncClipboard_${{ steps.version.outputs.content }}_macos_${{ matrix.cpu }}.dmg"
          path: "build/macos/SyncClipboard_${{ steps.version.outputs.content }}_macos_${{ matrix.cpu }}.dmg"