name: release

permissions:
  contents: write

on:
  push:
    tags: 
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build-progress.yml

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download last-job-built artifact SyncClipboard
        uses: actions/download-artifact@v3
        with:
          name: SyncClipboard

      - name: Download last-job-built artifact SyncClipboard.Server
        uses: actions/download-artifact@v3
        with:
          name: SyncClipboard.Server
          path: Server/

      - name: Download last-job-built artifact SyncClipboard.WinUI3
        uses: actions/download-artifact@v3
        with:
          name: SyncClipboard.WinUI3
          path: WinUI3/

      - name: Zip SyncClipboard.Server
        run: 7z a SyncClipboard.Server.zip Server\*

      - name: Zip SyncClipboard.WinUI3
        run: 7z a SyncClipboard.WinUI3.zip WinUI3\*      

      - name: Download last-job-built change log
        uses: actions/download-artifact@v3
        with:
          name: feature

      - name: Show change log
        run: |
          tree /f
          type feature.txt

      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: feature.txt
          files: |
            SyncClipboard.exe
            SyncClipboard.Server.zip
            SyncClipboard.WinUI3.zip